services:
    portfolio:
        image: node:lts-bullseye
        command: /bin/bash run.sh
        working_dir: /html5up-massively
        volumes:
            - ./pmahar.github.io:/html5up-massively
        ports:
            - "3000:3000"
        environment:
            HOST_OS: ${OS}
            NODE_ENV: development
            HOST: "0.0.0.0"
            PUBLIC_URL: http://localhost:3000
